version: '2.2'

services:
  mnogo-mesta-tracker:
    container_name: mnogo-mesta-tracker
    build:
      context: .
    command: npm run start:prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5252:3000"